import contextlib
import csv
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from src.generate_graph import GRAPH_FILES, generate_all_graphs
from src.literature_instances import FP6_LITERATURE_INSTANCES
from src.resource_estimate.configuration import (
    CCZ2T_L1_DS,
    CCZ2T_L2_DS,
    FIFTEEN_TO_ONE_DMS,
    FIFTEEN_TO_ONE_DXS,
    FIFTEEN_TO_ONE_DZS,
    SEARCH_DATA_DS,
    SWEPT_DATA_BLOCKS,
)
from src.resource_estimate.physical import QualtranPhysicalConfig
from src.resource_estimate.search import EvalRow, sweep

GENERATED_FILES = ("config.txt", "rows.json", "rows.csv", *GRAPH_FILES)

TOTAL_ERROR_BUDGET = 1 / 3

SYNTHESIS_ERROR_BUDGET = TOTAL_ERROR_BUDGET / 3
FACTORY_ERROR_BUDGET = TOTAL_ERROR_BUDGET / 3
DATA_ERROR_BUDGET = TOTAL_ERROR_BUDGET / 3
PHYSICAL_FAILURE_THRESHOLD = FACTORY_ERROR_BUDGET + DATA_ERROR_BUDGET

FINAL_FAILURE_THRESHOLD = 1e-2

PHYSICAL_CONFIG = QualtranPhysicalConfig(
    physical_error_rate=1e-4,
    cycle_time_us=0.4,
    qec_scheme="beverland",
    physical_failure_threshold=PHYSICAL_FAILURE_THRESHOLD,
    factory_error_budget=FACTORY_ERROR_BUDGET,
    data_error_budget=DATA_ERROR_BUDGET,
    factory="fifteen_to_one",
)


def _csv_columns(config: QualtranPhysicalConfig) -> list[str]:
    unused_prefix = "fifteen_to_one_" if config.factory == "ccz2t" else "ccz2t_"
    return [key for key in EvalRow.__annotations__ if not key.startswith(unused_prefix)]


def _config_text(
    config: QualtranPhysicalConfig,
    final_failure_threshold: float,
    synthesis_error_budget: float,
) -> str:
    """全点共通の再現条件をテキストで返す。"""
    lines = [
        "# generated by script/estimate_qualtran.py. Do not edit.",
        "",
        "[physical]",
        *[
            f"{key} = {value}"
            for key, value in asdict(config).items()
            if value is not None
            and key
            not in (
                "physical_failure_threshold",
                "factory_error_budget",
                "data_error_budget",
            )
        ],
        "",
        "[rotation_synthesis]",
        "model = BeverlandEtAlRotationCost",
        f"synthesis_error_budget = {synthesis_error_budget}",
        "",
        "[total_error_budget]",
        f"total_error_budget = {TOTAL_ERROR_BUDGET}",
        f"synthesis_error_budget = {synthesis_error_budget}",
        f"factory_error_budget = {config.factory_error_budget}",
        f"data_error_budget = {config.data_error_budget}",
        f"physical_failure_threshold = {config.physical_failure_threshold}",
        "",
        "[physical_search]",
        f"data_blocks = {list(SWEPT_DATA_BLOCKS)}",
        f"data_ds = {list(SEARCH_DATA_DS)}",
        *(
            [
                f"ccz2t_l1_ds = {list(CCZ2T_L1_DS)}",
                f"ccz2t_l2_ds = {list(CCZ2T_L2_DS)}",
            ]
            if config.factory == "ccz2t"
            else [
                f"fifteen_to_one_dxs = {list(FIFTEEN_TO_ONE_DXS)}",
                f"fifteen_to_one_dzs = {list(FIFTEEN_TO_ONE_DZS)}",
                f"fifteen_to_one_dms = {list(FIFTEEN_TO_ONE_DMS)}",
            ]
        ),
        "",
        "[final_failure_threshold]",
        f"final_failure_threshold = {final_failure_threshold}",
        "",
    ]
    return "\n".join(lines)


def cleanup_results(out_dir: Path) -> None:
    for name in GENERATED_FILES:
        with contextlib.suppress(FileNotFoundError):
            (out_dir / name).unlink()


def main() -> None:
    points = list(FP6_LITERATURE_INSTANCES)

    out_dir = Path(__file__).resolve().parent.parent / "results" / "qualtran"
    out_dir.mkdir(parents=True, exist_ok=True)

    cleanup_results(out_dir)

    (out_dir / "config.txt").write_text(
        _config_text(
            PHYSICAL_CONFIG,
            FINAL_FAILURE_THRESHOLD,
            SYNTHESIS_ERROR_BUDGET,
        )
    )

    csv_path = out_dir / "rows.csv"
    json_path = out_dir / "rows.json"
    columns = _csv_columns(PHYSICAL_CONFIG)

    with csv_path.open("w", newline="") as fp:
        csv.DictWriter(
            fp,
            fieldnames=columns,
            restval="",
            extrasaction="ignore",
            lineterminator="\n",
        ).writeheader()

    rows: list[dict[str, Any]] = []

    def on_row(row: dict[str, Any]) -> None:
        rows.append(row)

        with csv_path.open("a", newline="") as fp:
            csv.DictWriter(
                fp,
                fieldnames=columns,
                restval="",
                extrasaction="ignore",
                lineterminator="\n",
            ).writerow(row)

        json_path.write_text(
            json.dumps(
                rows,
                indent=2,
                allow_nan=False,
            )
        )

    sweep(
        points,
        PHYSICAL_CONFIG,
        FINAL_FAILURE_THRESHOLD,
        on_row=on_row,
        synthesis_error_budget=SYNTHESIS_ERROR_BUDGET,
    )

    graph_paths = generate_all_graphs(rows, out_dir)

    n_ok = sum(1 for row in rows if "error" not in row)

    print(f"rows: {len(rows)} (ok={n_ok}), graphs: {len(graph_paths)}, saved to: {out_dir}")

    if n_ok != len(rows):
        raise RuntimeError("some estimates failed; see error fields in rows.json")


if __name__ == "__main__":
    main()
