import argparse
import csv
import json
from collections.abc import Sequence
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import Any

from src.literature_instances import FP6_LITERATURE_INSTANCES
from src.resource_estimate.qualtran.configuration import (
    CCZ2T_L1_DS,
    CCZ2T_L2_DS,
    FIFTEEN_TO_ONE_DMS,
    FIFTEEN_TO_ONE_DXS,
    FIFTEEN_TO_ONE_DZS,
    SEARCH_DATA_DS,
    SWEPT_DATA_BLOCKS,
)
from src.resource_estimate.qualtran.physical import QualtranPhysicalConfig
from src.resource_estimate.qualtran.search import EvalRow, sweep

TOTAL_ERROR_BUDGET = 1 / 3

SYNTHESIS_ERROR_BUDGET = TOTAL_ERROR_BUDGET / 3
FACTORY_ERROR_BUDGET = TOTAL_ERROR_BUDGET / 3
DATA_ERROR_BUDGET = TOTAL_ERROR_BUDGET / 3
PHYSICAL_FAILURE_THRESHOLD = FACTORY_ERROR_BUDGET + DATA_ERROR_BUDGET

FINAL_FAILURE_THRESHOLD = 1e-2

PHYSICAL_CONFIG = QualtranPhysicalConfig(
    physical_error_rate=1e-4,
    cycle_time_us=0.4,
    qec_scheme="beverland",
    physical_failure_threshold=PHYSICAL_FAILURE_THRESHOLD,
    factory_error_budget=FACTORY_ERROR_BUDGET,
    data_error_budget=DATA_ERROR_BUDGET,
    factory="fifteen_to_one",
)


def _csv_columns(config: QualtranPhysicalConfig) -> list[str]:
    unused_prefix = "fifteen_to_one_" if config.factory == "ccz2t" else "ccz2t_"
    return [key for key in EvalRow.__annotations__ if not key.startswith(unused_prefix)]


def _config_text(
    config: QualtranPhysicalConfig,
    final_failure_threshold: float,
    synthesis_error_budget: float,
) -> str:
    """全点共通の再現条件をテキストで返す。"""
    lines = [
        "# generated by script/estimate_qualtran.py. Do not edit.",
        "",
        "[algorithm]",
        "bloq = ShorDLP",
        "",
        "[physical]",
        *[
            f"{key} = {value}"
            for key, value in asdict(config).items()
            if value is not None
            and key
            not in (
                "physical_failure_threshold",
                "factory_error_budget",
                "data_error_budget",
            )
        ],
        "",
        "[rotation_synthesis]",
        "model = BeverlandEtAlRotationCost",
        f"synthesis_error_budget = {synthesis_error_budget}",
        "",
        "[total_error_budget]",
        f"total_error_budget = {TOTAL_ERROR_BUDGET}",
        f"synthesis_error_budget = {synthesis_error_budget}",
        f"factory_error_budget = {config.factory_error_budget}",
        f"data_error_budget = {config.data_error_budget}",
        f"physical_failure_threshold = {config.physical_failure_threshold}",
        "",
        "[physical_search]",
        f"data_blocks = {list(SWEPT_DATA_BLOCKS)}",
        f"data_ds = {list(SEARCH_DATA_DS)}",
        *(
            [
                f"ccz2t_l1_ds = {list(CCZ2T_L1_DS)}",
                f"ccz2t_l2_ds = {list(CCZ2T_L2_DS)}",
            ]
            if config.factory == "ccz2t"
            else [
                f"fifteen_to_one_dxs = {list(FIFTEEN_TO_ONE_DXS)}",
                f"fifteen_to_one_dzs = {list(FIFTEEN_TO_ONE_DZS)}",
                f"fifteen_to_one_dms = {list(FIFTEEN_TO_ONE_DMS)}",
            ]
        ),
        "",
        "[final_failure_threshold]",
        f"final_failure_threshold = {final_failure_threshold}",
        "",
    ]
    return "\n".join(lines)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Qualtran resource estimation for Shor DLP.")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="出力先の基準ディレクトリ (既定: results/qualtran)。"
        "実行日時フォルダがこの下に作られる",
    )
    return parser.parse_args(argv)


def default_base_dir() -> Path:
    return Path(__file__).resolve().parent.parent / "results" / "qualtran"


def _run_timestamp(now: datetime | None = None) -> str:
    return (now or datetime.now()).strftime("%Y%m%d_%H%M%S")


def resolve_out_dir(base: Path, timestamp: str | None = None) -> Path:
    """基準ディレクトリの下に実行日時フォルダを切る。同秒の衝突時は連番を付ける。"""
    stamp = timestamp or _run_timestamp()
    out_dir = base / stamp
    if timestamp is not None:
        return out_dir
    suffix = 0
    while out_dir.exists():
        suffix += 1
        out_dir = base / f"{stamp}_{suffix:02d}"
    return out_dir


def main(argv: Sequence[str] | None = None, timestamp: str | None = None) -> Path:
    args = parse_args(argv)
    points = list(FP6_LITERATURE_INSTANCES)

    base = args.out_dir if args.out_dir is not None else default_base_dir()
    out_dir = resolve_out_dir(base, timestamp)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "config.txt").write_text(
        _config_text(
            PHYSICAL_CONFIG,
            FINAL_FAILURE_THRESHOLD,
            SYNTHESIS_ERROR_BUDGET,
        )
    )

    csv_path = out_dir / "rows.csv"
    json_path = out_dir / "rows.json"
    columns = _csv_columns(PHYSICAL_CONFIG)

    with csv_path.open("w", newline="") as fp:
        csv.DictWriter(
            fp,
            fieldnames=columns,
            restval="",
            extrasaction="ignore",
            lineterminator="\n",
        ).writeheader()

    rows: list[dict[str, Any]] = []

    def on_row(row: dict[str, Any]) -> None:
        rows.append(row)

        with csv_path.open("a", newline="") as fp:
            csv.DictWriter(
                fp,
                fieldnames=columns,
                restval="",
                extrasaction="ignore",
                lineterminator="\n",
            ).writerow(row)

        json_path.write_text(
            json.dumps(
                rows,
                indent=2,
                allow_nan=False,
            )
        )

    sweep(
        points,
        PHYSICAL_CONFIG,
        FINAL_FAILURE_THRESHOLD,
        on_row=on_row,
        synthesis_error_budget=SYNTHESIS_ERROR_BUDGET,
    )

    n_ok = sum(1 for row in rows if "error" not in row)

    print(f"rows: {len(rows)} (ok={n_ok}), saved to: {out_dir}")

    if n_ok != len(rows):
        raise RuntimeError("some estimates failed; see error fields in rows.json")

    return out_dir


if __name__ == "__main__":
    main()  # parse_args() が sys.argv を読む
